"""Shared helpers for the repo-level tooling in `tools/`.

These scripts run with the repo's uv environment (`uv run python tools/...`)
but deliberately keep their imports minimal so that `check_generated.py` can
run as a pre-commit hook without importing pandas or the wandb client.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

PROVENANCE_FILENAME = ".provenance.json"


def repo_root() -> Path:
    """Absolute path of the paper repository root (the directory holding references.bib)."""
    here = Path(__file__).resolve()
    for candidate in (here.parent.parent, *here.parents):
        if (candidate / "references.bib").is_file() and (candidate / "docs").is_dir():
            return candidate
    raise SystemExit("error: could not locate the paper repository root (no references.bib found)")


def root_bib(root: Path | None = None) -> Path:
    return (root or repo_root()) / "references.bib"


def paper_dirs(root: Path | None = None) -> list[Path]:
    """Every document directory that participates in bib materialization.

    A directory qualifies if it contains a `main.tex`. That covers papers,
    theses and topic advertisements alike without a registry to keep in sync.
    """
    root = root or repo_root()
    return sorted(p.parent for p in (root / "docs").glob("*/main.tex"))


def rel(path: Path, root: Path | None = None) -> str:
    """Repo-relative POSIX path, for stable output and stable provenance files."""
    return path.resolve().relative_to((root or repo_root()).resolve()).as_posix()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_provenance(figures_dir: Path) -> dict:
    path = figures_dir / PROVENANCE_FILENAME
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise SystemExit(f"error: {path} is not valid JSON: {exc}") from exc


def write_provenance(figures_dir: Path, data: dict) -> None:
    path = figures_dir / PROVENANCE_FILENAME
    figures_dir.mkdir(parents=True, exist_ok=True)
    # sort_keys + trailing newline keeps the diff minimal and the file stable.
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


TEMPLATE_CONFIG = ".template.yml"


def _yaml():
    try:
        import yaml
    except ModuleNotFoundError:  # pragma: no cover - depends on environment
        raise SystemExit(
            "error: pyyaml is not installed. Run `uv sync` and invoke these scripts "
            "with `uv run python tools/...`."
        ) from None
    return yaml


def templates_dir(root: Path | None = None) -> Path:
    return (root or repo_root()) / "tools" / "templates"


def list_templates(root: Path | None = None) -> list[str]:
    """Template names, i.e. directories under tools/templates/ with a main.tex."""
    return sorted(p.parent.name for p in templates_dir(root).glob("*/main.tex"))


def read_template(name: str, root: Path | None = None) -> dict:
    """Load tools/templates/<name>/template.yml, with the resolved asset paths."""
    root = root or repo_root()
    directory = templates_dir(root) / name
    if not (directory / "main.tex").is_file():
        available = ", ".join(list_templates(root)) or "(none)"
        raise SystemExit(f"error: no template named '{name}'. Available: {available}")

    config_path = directory / "template.yml"
    config = {}
    if config_path.is_file():
        config = _yaml().safe_load(config_path.read_text()) or {}

    config["name"] = name
    config["dir"] = directory
    config["main_tex"] = directory / "main.tex"
    # Assets are written relative to tools/templates/ so that templates can share
    # files (researchcommon.sty, orcid.pdf) instead of duplicating them.
    config["asset_paths"] = [templates_dir(root) / a for a in config.get("assets", [])]
    return config


def read_document_template(paper: Path) -> dict:
    """Which template a document uses, and the hash of its pristine main.tex."""
    path = paper / TEMPLATE_CONFIG
    if not path.is_file():
        return {}
    return _yaml().safe_load(path.read_text()) or {}


def write_document_template(paper: Path, name: str, main_tex_sha256: str) -> None:
    path = paper / TEMPLATE_CONFIG
    path.write_text(
        "# Generated by tools/set_template.py — do not edit.\n"
        "#\n"
        "# `main_tex_sha256` is the hash of main.tex as this template generated it.\n"
        "# `make set-template` compares against it and refuses to overwrite local\n"
        "# edits unless you pass FORCE=1.\n"
        f"template: {name}\n"
        f"main_tex_sha256: {main_tex_sha256}\n"
    )


def read_yaml(path: Path) -> dict:
    """Parse a YAML mapping, tolerating an empty or absent file."""
    if not path.is_file():
        return {}
    return _yaml().safe_load(path.read_text()) or {}


# ---------------------------------------------------------------------------
# Configuration: `paper.yml` plus one config per figure and per table.
#
# There is no central registry of datasets. A figure is a file — `figures/
# <name>.yml` — that says where its numbers come from AND how it is drawn, and
# `paper.yml` supplies only what every figure would otherwise repeat: the W&B
# connection and the house style.
#
# `data/wandb.lock.yml` records what a `make fetch` actually resolved each
# config's query to — the run IDs — plus a hash of the query itself.
# `check_generated.py` compares the two, which is how "you changed the query but
# never re-fetched" becomes a build failure instead of a silently wrong number.
# ---------------------------------------------------------------------------

PAPER_CONFIG = "paper.yml"
LOCK_FILENAME = "wandb.lock.yml"
KINDS = ("figures", "tables")


def data_dir(root: Path | None = None) -> Path:
    """`data/` — the committed W&B cache."""
    path = (root or repo_root()) / "data"
    path.mkdir(parents=True, exist_ok=True)
    return path


def cache_path(kind: str, name: str, root: Path | None = None) -> Path:
    """`data/<kind>/<name>.csv` — one config's fetched numbers.

    Namespaced by kind so that a figure and a table may share a name, and CSV
    rather than Parquet so that it renders in the GitHub UI: a pull request that
    moves the paper's numbers shows the move as a reviewable text diff.
    """
    return data_dir(root) / kind / f"{name}.csv"


def lock_path(root: Path | None = None) -> Path:
    return data_dir(root) / LOCK_FILENAME


def config_dir(kind: str, root: Path | None = None) -> Path:
    if kind not in KINDS:
        raise SystemExit(f"error: unknown config kind '{kind}' (expected one of {KINDS})")
    return (root or repo_root()) / kind


def config_paths(kind: str, root: Path | None = None) -> list[Path]:
    """Every config of one kind. Leading-underscore files are reserved."""
    directory = config_dir(kind, root)
    if not directory.is_dir():
        return []
    return sorted(p for p in directory.glob("*.yml") if not p.name.startswith("_"))


def config_names(kind: str, root: Path | None = None) -> list[str]:
    return [p.stem for p in config_paths(kind, root)]


def all_configs(root: Path | None = None) -> list[tuple[str, str]]:
    """Every (kind, name) pair in the repository, in a stable order."""
    return [(kind, name) for kind in KINDS for name in config_names(kind, root)]


def read_paper_config(root: Path | None = None) -> dict:
    """Parse `paper.yml` — the defaults every config inherits."""
    root = root or repo_root()
    config = read_yaml(root / PAPER_CONFIG)
    if not config:
        raise SystemExit(
            f"error: {PAPER_CONFIG} is missing or empty. It holds the W&B connection "
            f"and the house style that every figure inherits. See README.md."
        )
    config.setdefault("wandb", {})
    config.setdefault("style", {})
    config.setdefault("round", 6)
    return config


def _merge(base: dict, override: dict) -> dict:
    """Shallow-recursive merge: `override` wins, nested mappings merge."""
    result = dict(base)
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _merge(result[key], value)
        else:
            result[key] = value
    return result


def load_config(kind: str, name: str, root: Path | None = None) -> dict:
    """One figure or table config, with `paper.yml` folded in.

    The result always carries `kind`, `name`, `document`, `data` and the
    kind-specific rendering block, so every consumer sees the same shape.
    """
    root = root or repo_root()
    path = config_dir(kind, root) / f"{name}.yml"
    if not path.is_file():
        available = ", ".join(config_names(kind, root)) or "(none)"
        raise SystemExit(f"error: no {kind[:-1]} config at {rel(path, root)}. Have: {available}")

    paper = read_paper_config(root)
    config = read_yaml(path) or {}

    if not config.get("document"):
        raise SystemExit(
            f"error: {rel(path, root)} has no `document:` — it does not say which "
            f"document under docs/ it belongs to."
        )

    data = _merge({"round": paper["round"]}, config.get("data") or {})
    data = _merge(paper["wandb"], data)

    render_key = "plot" if kind == "figures" else "table"
    render = _merge(paper["style"], config.get(render_key) or {})

    return {
        "kind": kind,
        "name": name,
        "path": path,
        "document": config["document"],
        "data": data,
        render_key: render,
        "raw": config,
    }


def spec_sha256(config: dict) -> str:
    """Content hash of one config's *query*, independent of key order.

    Covers the entity, the project and the resolved `data:` block — everything
    that decides which runs are matched and which columns are written. The
    rendering block is deliberately excluded: restyling a figure does not
    invalidate its data.
    """
    canonical = json.dumps(config["data"], sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode()).hexdigest()


def lock_key(kind: str, name: str) -> str:
    return f"{kind}/{name}"


def read_lock(root: Path | None = None) -> dict:
    return read_yaml(lock_path(root))


def write_lock(data: dict, root: Path | None = None) -> None:
    header = (
        "# Generated by tools/fetch.py — do not edit.\n"
        "#\n"
        "# The exact W&B runs behind every number in this paper, one entry per figure\n"
        "# or table config. `make fetch` re-reads these IDs; `make fetch REFRESH=1`\n"
        "# re-runs the queries and rewrites this file, reporting which runs entered\n"
        "# and left.\n"
        "#\n"
        "# `spec_sha256` is the hash of a config's `data:` block as it stood when the\n"
        "# data was fetched. `make check-generated` fails when a config has drifted\n"
        "# from it.\n"
    )
    lock_path(root).write_text(
        header + _yaml().safe_dump(data, sort_keys=True, default_flow_style=False)
    )


def git(*args: str, cwd: Path | None = None, check: bool = True) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=cwd or repo_root(),
        capture_output=True,
        text=True,
        check=False,
    )
    if check and result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f"error: git {' '.join(args)} failed with code {result.returncode}")
    return result.stdout.strip()


def working_tree_is_clean(root: Path | None = None) -> bool:
    return git("status", "--porcelain", cwd=root) == ""


def ensure_remote(name: str, url: str, root: Path | None = None) -> None:
    """Create the named git remote, or point an existing one at `url`.

    Shared by every sync path in this directory: the Overleaf satellite, the
    upstream template and the vendored subtrees each address their counterpart
    through a remote named after it, so the URL lives in one tracked config file
    rather than in the shell history of whoever last ran the command.
    """
    root = root or repo_root()
    if name not in git("remote", cwd=root).splitlines():
        git("remote", "add", name, url, cwd=root)
        print(f"added git remote '{name}' -> {url}")
        return
    current = git("remote", "get-url", name, cwd=root)
    if current != url:
        git("remote", "set-url", name, url, cwd=root)
        print(f"updated git remote '{name}': {current} -> {url}")


def require_clean_tree(root: Path, action: str) -> None:
    """Refuse to run a sync against a dirty working tree.

    Every sync command here moves *committed* history, so an unclean tree means
    the thing you are looking at is not the thing that would move.
    """
    if not working_tree_is_clean(root):
        raise SystemExit(
            f"error: working tree is dirty. {action} moves committed history only, so "
            f"an unclean tree means the result would not match what you are looking at. "
            f"Commit or stash first."
        )


class Reporter:
    """Collects failures so a check can report *all* problems, not just the first."""

    def __init__(self, title: str) -> None:
        self.title = title
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)

    def finish(self) -> int:
        for message in self.warnings:
            print(f"  warn   {message}")
        for message in self.errors:
            print(f"  ERROR  {message}")
        if self.errors:
            print(f"\n{self.title}: {len(self.errors)} problem(s). See AGENTS.md.")
            return 1
        print(
            f"{self.title}: ok" + (f" ({len(self.warnings)} warning(s))" if self.warnings else "")
        )
        return 0
